#include <server.h>
#include <BoardGame.h>
#include <Minesweeper.h>

using namespace ucm;

// Do not edit this file in any way whatsoever. If you make any changes, they will be discarded.

int main(int argc, char** argv){

    CrowServer server(argc, argv);

    BoardGame* game = new Minesweeper(9, 9, 10);

    server.renderHTML("/", "index.html");

    server.route("/init", [&](const request& req, response& res){

        game->reset();
        
        json board = game->getBoard(); 

        res.sendJSON(board);
    });

    server.route("/handle", [&](const request& req, response& res){

        if (req.has_params({"x", "y", "btn"})){

            std::string xS = req.url_params.get("x");
            std::string yS = req.url_params.get("y");
            std::string btn = req.url_params.get("btn");

            int x = stoi(xS);
            int y = stoi(yS);
            MouseButton button;
            if (btn == "left"){
                button = left;
            }
            else if (btn == "right"){
                button = right;
            }
            else{
                button = unknown;
            }

            game->handle(x, y, button);

            json board = game->getBoard();

            res.sendJSON(board);
        }

        else{
            res.sendError400();
        }
    });

    server.run();
}
